# Generated by Django 4.0.6 on 2023-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
