# Generated by Django 4.0.6 on 2023-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='vegetable/receipe'),
        ),
    ]
